---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelease-frontend
  labels:
    travelease.io/name: travelease-frontend
    app.kubernetes.io/instance: travelease-deploy
    app.kubernetes.io/name: travelease-frontend
    app.kubernetes.io/part-of: travelease-deploy
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      travelease.io/name: travelease-frontend
  template:
    metadata:
      labels:
        travelease.io/name: travelease-frontend  
        app.kubernetes.io/instance: travelease-deploy
        app.kubernetes.io/component: frontendproxy
        app.kubernetes.io/name: travelease-frontend

    spec:
      serviceAccountName: travelease-deploy   
      containers:
        - name: travelease-frontend
          image: 831926586767.dkr.ecr.us-east-1.amazonaws.com/travelease/frontend:16108561235
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: service
          env:
            - name: VITE_LOGIN_API_URL
              value: "/api/login"
            - name: VITE_PAYMENT_API_URL
              value: "/api/payment"
            - name: VITE_BOOKING_API_URL
              value: "/api/booking"   
          
