name: ZAP Full Scan

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Full ZAP Scan against live site

    steps:
      - name: Run ZAP Full Scan via Docker
        run: |
          docker run --rm --user 0 -v ${{ github.workspace }}:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t https://travelease.bhaveshdevops.in \
            -r zap-report.html \
            -I -j

      - name: List files after scan
        run: ls -al

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: zap-report.html
